//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ControlCenter : DroneDeliverySimulationComponent
{
	public virtual List<Warehouse> WarehouseList
	{
		get;
		set;
	}

	public virtual List<Drone> DroneList
	{
		get;
		set;
	}

	public string ID
	{
		get;
		set;
	}

	public virtual void FindTheNearestDroneToTheWarehouse(Warehouse warehouse)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool IssueOrderToDrone()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Log()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateWarehouses()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateDrones()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Update()
	{
		throw new System.NotImplementedException();
	}

}

