//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using BasicVector;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Drone : DroneDeliverySimulationComponent
{
	public virtual Vector CurrentLocation
	{
		get;
		set;
	}

	public virtual DroneStatus CurrentStatus
	{
		get;
		set;
	}

	public virtual int MaxWeight
	{
		get;
		set;
	}

	public virtual int CurrentWeight
	{
		get;
		set;
	}

	public virtual List<Package> PackagesOnboard
	{
		get;
		set;
	}

	public virtual int Speed
	{
		get;
		set;
	}

	public virtual List <Instruction> Instruction
	{
		get;
		set;
	}

	public virtual string ID
	{
		get;
		set;
	}

	public virtual void MoveTo(Vector TargetPos)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Log()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool UnloadPackage(Package Package)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeStatus()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool ExecuteOrder(Instruction Order)
	{
		throw new System.NotImplementedException();
	}

}

