//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Instruction
{
	public virtual Vector TargetPosition
	{
		get;
		set;
	}

	public virtual Task Task
	{
		get;
		set;
	}

	public virtual bool OrderCompleted
	{
		get;
		set;
	}

	public virtual Package Package
	{
		get;
		set;
	}

	public virtual void SetOrderAsCompleted()
	{
		throw new System.NotImplementedException();
	}

}

