//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Package
{
	public virtual Recipient Recipient
	{
		get;
		set;
	}

	public virtual int Weight
	{
		get;
		set;
	}

	public virtual void GetPackageInfo()
	{
		throw new System.NotImplementedException();
	}

}

